name: Deploy to EC2 via Docker

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}
        
    - name: Build Docker image
      run: docker build -t mywebapp:v1 .

    - name: Copy files to EC2
      run: scp -o StrictHostKeyChecking=no Dockerfile signup.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

    - name: Deploy container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/app
          docker build -t mywebapp:v1 .
          docker stop myweb-container || true
          docker rm myweb-container || true
          docker run -d -p 9090:80 --name myweb-container mywebapp:v1
        EOF
